spring.application.name=job-portal-pro
spring.datasource.url=jdbc:postgresql://dpg-d7ssdsl7vvec73ca7tsg-a:5432/job_portal_db_krur
spring.datasource.username=job_portal_db_krur_user
spring.datasource.password=6n8dCH1X9LnHYVhBiK8PYSy3fLEjMwyd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.ssl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
